import type { Hotspot } from './types';

export const hotspots: Hotspot[] = [
	{
		startTime: 141,
		endTime: 149,
		//top: 60,
		//left: 295,
		//height: 180,
		//width: 140,
		title: 'Helpful Hints',
		text: 'Scene 3- HH_charge your auto-injector.mp4 - 26 second duration.',
		link: '/scene/Scene 3- HH_charge your auto-injector.mp4',
	},
	{
		startTime: 181,
		endTime: 189,
		title: 'Helpful Hints',
		text: 'Scene 4- HH_prepare step 1.mp4 - 20 second duration.',
		link: '/scene/Scene 4- HH_prepare step 1.mp4',
	},
	{
		startTime: 192,
		endTime: 201,
		title: 'Helpful Hints',
		text: 'Scene 5- HH_prepare step 2.mp4 - 36 second duration.',
		link: '/scene/Scene 5- HH_prepare step 2.mp4',
	},
	{
		startTime: 204,
		endTime: 208,
		title: 'Helpful Hints',
		text: 'Scene 6- HH_prepare step 3.mp4 - 09 second duration.',
		link: '/scene/Scene 6- HH_prepare step 3.mp4',
	},
	{
		startTime: 210,
		endTime: 230,
		title: 'Helpful Hints',
		text: 'Scene 7- HH_mixing step 4.mp4 - 39 second duration.',
		link: '/scene/Scene 7- HH_mixing step 4.mp4',
	},
	{
		startTime: 233,
		endTime: 250,
		title: 'Helpful Hints',
		text: 'Scene 8- HH_mixing step 5.mp4 - 18 second duration.',
		link: '/scene/Scene 8- HH_mixing step 5.mp4',
	},
	{
		startTime: 276,
		endTime: 286,
		title: 'Helpful Hints',
		text: 'Scene 7- HH_inject step 7.mp4 - 38 second duration.',
		link: '/scene/Scene 7- HH_inject step 7.mp4',
	},
	{
		startTime: 289,
		endTime: 305,
		title: 'Helpful Hints',
		text: 'Scene 11- HH_inject step 8.mp4 - 15 second duration.',
		link: '/scene/Scene 11- HH_inject step 8.mp4',
	},
	{
		startTime: 307,
		endTime: 340,
		title: 'Helpful Hints',
		text: 'Scene 12- HH_inject step 9.mp4 - 38 second duration.',
		link: '/scene/Scene 12- HH_inject step 9.mp4',
	},
	{
		startTime: 394,
		endTime: 416,
		title: 'Helpful Hints',
		text: 'Scene 16- HH_after injection step 12.mp4 - 17 second duration.',
		link: '/scene/Scene 16- HH_after injection step 12.mp4',
	},
];
